"""add cgpa and branch to resumes

Revision ID: 2ff530455fdc
Revises: f15967cb8bab
Create Date: 2026-08-16 20:38:06.808478

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ff530455fdc'
down_revision: Union[str, Sequence[str], None] = 'f15967cb8bab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('cgpa', sa.Float(), nullable=True))
    op.add_column('resumes', sa.Column('branch', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'branch')
    op.drop_column('resumes', 'cgpa')
    # ### end Alembic commands ###
