"""add candidate_name to resumes

Revision ID: 7a7fb117c4f3
Revises: 2ff530455fdc
Create Date: 2026-08-16 21:14:57.342430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a7fb117c4f3'
down_revision: Union[str, Sequence[str], None] = '2ff530455fdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resumes', sa.Column('candidate_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resumes', 'candidate_name')
    # ### end Alembic commands ###
