"""add soft_skills_mentioned to jds

Revision ID: f15967cb8bab
Revises: c4c70e7c0a13
Create Date: 2026-08-16 20:10:28.153404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15967cb8bab'
down_revision: Union[str, Sequence[str], None] = 'c4c70e7c0a13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jds', sa.Column('soft_skills_mentioned', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jds', 'soft_skills_mentioned')
    # ### end Alembic commands ###
